### ISSUE TITLE
How could I add hotkeys?

### ISSUE THREAD

**Issue by comix4k** [VortexShrimp/imgui-csgo-sdk#3]
I tried using csgosimples hotkey thingy but I was so confused and my brain went all over the place. Do you know how i could do a hotkey bind where it records your buttons. so if i want to change XBUTTON1 To XBUTTON2 in the menu without going into the source. This is the first time ive used a base with imgui.

**Comment by VortexShrimp** [comment]
Please see #1 where it was explained how you would implement such a feature.
