### ISSUE TITLE
Help with viewmodel changer

### ISSUE THREAD

**Issue by comix4k** [VortexShrimp/imgui-csgo-sdk#4]
I've added everything I wanted to add. I've added the view model changer but the thing is it doesn't go above 5
I guess it's changing the *legit* value.

I think I may need to add this as I saw in aristos and zukrass.

	interfaces::console->get_convar("viewmodel_offset_x")->callbacks.set_size(false);
	interfaces::console->get_convar("viewmodel_offset_y")->callbacks.set_size(false);
	interfaces::console->get_convar("viewmodel_offset_z")->callbacks.set_size(false);

![image](https://user-images.githubusercontent.com/69500838/99242891-d88f9700-27cd-11eb-88f3-5f74ae58ce65.png)

but i get these errors and i dont know a fix

**Comment by VortexShrimp** [comment]
Right, you do need to set the `callbacks.size` size to 0, but I'm not sure why you are fiddling with the `viewmodel_offset` cvars. You should probably remove those.

Here is how you would go about making a FOV changer by forcing the cvar with this base.
```cpp
float fov = 120.f;
auto viewmodel_fov = interfaces::console->get_convar("viewmodel_fov");
viewmodel_fov->callbacks.size = 0;
viewmodel_fov->set_value(fov); // Of course you would set this to your global fov variable
```

If you want to do it the correct way though, you should hook:
- `OverrideView()` (index 18 of clientmode)
- `GetViewmodelFov()` (index 35 clientmode)

There are plenty of resources on this online. Good luck.
